baseurl = "https://www.patrio.blog/"
title = "Patrio's blog site"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Patrik Drhlík"
disqusShortname = "patrioblog"
googleAnalytics = "UA-105666525-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Patrik Drhlík"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Patrio's blog site"
    description = "Mostly about R"
    github = "https://github.com/pdrhlik"
    linkedin = "https://linkedin.com/in/patrik-drhlik/"
    twitter = "https://twitter.com/PatrioScraper"
    email = "patrik.drhlik@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    mathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML"

[Permalinks]
    post = "/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

# [[menu.main]]
#    name = "Projects"
#    url = "/project/"
#    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
